export const mockCompanies = [
  {
    id: 'c1',
    name: 'BâtiPro Construct',
    siren: '123456789',
    contactEmail: 'admin@batipro.fr',
    planType: 'Enterprise',
    status: 'Active',
    memberCount: 45,
    activeSites: 12,
    monthlyFee: 999,
    renewalDate: '2024-12-01',
  },
  {
    id: 'c2',
    name: 'Artisans Réunis',
    siren: '987654321',
    contactEmail: 'contact@artisans-reunis.fr',
    planType: 'Starter',
    status: 'Active',
    memberCount: 5,
    activeSites: 2,
    monthlyFee: 49,
    renewalDate: '2024-10-15',
  },
  {
    id: 'c3',
    name: 'GrosOeuvre SA',
    siren: '555444333',
    contactEmail: 'direction@grosoeuvre.com',
    planType: 'Pro',
    status: 'Suspended',
    memberCount: 20,
    activeSites: 0,
    monthlyFee: 299,
    renewalDate: '2024-08-01',
  },
];

export const mockSites = [
  {
    id: 's1',
    companyId: 'c1',
    name: 'Tour Montparnasse Rénovation',
    address: '33 Avenue du Maine, 75015 Paris',
    managerName: 'Jean Dupont',
    status: 'En cours',
    budget: 5000000,
    workersCount: 25,
  },
  {
    id: 's2',
    companyId: 'c1',
    name: 'Immeuble de Bureaux Lyon',
    address: '10 Rue de la République, 69001 Lyon',
    managerName: 'Marie Curie',
    status: 'En retard',
    budget: 1200000,
    workersCount: 15,
  },
  {
    id: 's3',
    companyId: 'c2',
    name: 'Rénovation Maison Individuelle',
    address: '15 Chemin des Pins, 33000 Bordeaux',
    managerName: 'Paul Martin',
    status: 'Terminé',
    budget: 80000,
    workersCount: 3,
  },
];

export const mockWorkers = [
  {
    id: 'w1',
    companyId: 'c1',
    name: 'Jean Dupont',
    role: 'Chef de chantier',
    siteAssigned: 's1',
    phone: '0612345678',
    hoursLoggedThisWeek: 39,
  },
  {
    id: 'w2',
    companyId: 'c1',
    name: 'Luc Durand',
    role: 'Compagnon',
    siteAssigned: 's1',
    phone: '0698765432',
    hoursLoggedThisWeek: 35,
  },
  {
    id: 'w3',
    companyId: 'c2',
    name: 'Paul Martin',
    role: 'Chef de chantier',
    siteAssigned: 's3',
    phone: '0655443322',
    hoursLoggedThisWeek: 42,
  },
  {
    id: 'w4',
    companyId: 'c1',
    name: 'Marc Leroi',
    role: 'Compagnon',
    siteAssigned: 's2',
    phone: '0677889900',
    hoursLoggedThisWeek: 20,
  },
];

export const mockAuditLogs = [
  {
    id: 'l1',
    timestamp: '2024-09-01T08:30:00Z',
    actor: 'Super Admin',
    companyId: 'system',
    companyName: 'System',
    action: 'Created new company BâtiPro Construct',
    level: 'INFO',
  },
  {
    id: 'l2',
    timestamp: '2024-09-02T10:15:00Z',
    actor: 'Patron',
    companyId: 'c1',
    companyName: 'BâtiPro Construct',
    action: 'Added new site Tour Montparnasse Rénovation',
    level: 'INFO',
  },
  {
    id: 'l3',
    timestamp: '2024-09-03T14:45:00Z',
    actor: 'Chef de chantier (Jean Dupont)',
    companyId: 'c1',
    companyName: 'BâtiPro Construct',
    action: 'Reported site En retard',
    level: 'WARNING',
  },
  {
    id: 'l4',
    timestamp: '2024-09-04T09:00:00Z',
    actor: 'System',
    companyId: 'c3',
    companyName: 'GrosOeuvre SA',
    action: 'Suspended account due to unpaid dues',
    level: 'ERROR',
  },
];

export const mockStats = {
  mrr: 1347,
  activeTenants: 2,
  totalActiveSites: 14,
  systemHealth: 99.9,
};

export const mockUsers = [
  {
    id: 'u1',
    name: 'Alice System',
    email: 'super@buildsync.com',
    role: 'super_admin',
    companyId: 'system',
  },
  {
    id: 'u2',
    name: 'Boss Batipro',
    email: 'admin@batipro.fr',
    role: 'company_admin',
    companyId: 'c1',
  },
  {
    id: 'u3',
    name: 'Jean Dupont',
    email: 'j.dupont@batipro.fr',
    role: 'site_manager',
    companyId: 'c1',
    workerId: 'w1',
  },
  {
    id: 'u4',
    name: 'Luc Durand',
    email: 'l.durand@batipro.fr',
    role: 'worker',
    companyId: 'c1',
    workerId: 'w2',
  },
];

export const mockEquipment = {
  heavyMachinery: [
    {
      id: 'hm1',
      companyId: 'c1',
      name: 'Pelleteuse Volvo EC220E',
      model: 'EC220E',
      serialNumber: 'VOL220E99812',
      assignedSiteId: 's1',
      status: 'En service',
      nextInspectionDate: '2025-05-15',
      hourlyCost: 45,
    },
    {
      id: 'hm2',
      companyId: 'c1',
      name: 'Grue à tour Potain',
      model: 'MDT 219',
      serialNumber: 'POT2194455',
      assignedSiteId: 's1',
      status: 'En service',
      nextInspectionDate: '2024-11-20',
      hourlyCost: 120,
    },
    {
      id: 'hm3',
      companyId: 'c1',
      name: 'Chargeuse JCB 409',
      model: '409',
      serialNumber: 'JCB4091122',
      assignedSiteId: null,
      status: 'Disponible',
      nextInspectionDate: '2025-02-10',
      hourlyCost: 35,
    },
  ],
  lightTools: [
    {
      id: 'lt1',
      companyId: 'c1',
      name: 'Perforateur Hilti TE 60',
      category: 'Électroportatif',
      currentHolderWorkerId: 'w2',
      assignedSiteId: 's1',
      condition: 'Bon',
    },
    {
      id: 'lt2',
      companyId: 'c1',
      name: 'Scie circulaire Makita',
      category: 'Électroportatif',
      currentHolderWorkerId: 'w4',
      assignedSiteId: 's2',
      condition: 'Usé',
    },
    {
      id: 'lt3',
      companyId: 'c1',
      name: 'Niveau laser Bosch',
      category: 'Mesure',
      currentHolderWorkerId: null,
      assignedSiteId: 's1',
      condition: 'Neuf',
    },
  ]
};
